/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "primary": "#ebffe2",
        "surface-container": "#201f1f",
        "on-secondary-fixed": "#320046",
        "on-primary-fixed": "#002203",
        "surface-dim": "#131313",
        "secondary": "#ecb1ff",
        "outline-variant": "#3b4b37",
        "primary-container": "#00ff41",
        "on-primary-fixed-variant": "#00530e",
        "secondary-fixed": "#f9d8ff",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#b9ccb2",
        "tertiary-fixed": "#ffdad6",
        "on-secondary-fixed-variant": "#75009e",
        "tertiary-container": "#ffd2cd",
        "inverse-on-surface": "#313030",
        "primary-fixed-dim": "#00e639",
        "inverse-primary": "#006e16",
        "on-tertiary-container": "#c40015",
        "on-secondary-container": "#480063",
        "tertiary-fixed-dim": "#ffb4ab",
        "outline": "#84967e",
        "on-primary-container": "#007117",
        "primary-fixed": "#72ff70",
        "on-primary": "#003907",
        "surface": "#131313",
        "surface-container-high": "#2a2a2a",
        "on-tertiary": "#690006",
        "on-tertiary-fixed-variant": "#93000c",
        "on-tertiary-fixed": "#410002",
        "background": "#131313",
        "on-error": "#690005",
        "surface-bright": "#393939",
        "on-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "on-secondary": "#520070",
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#ecb1ff",
        "surface-tint": "#00e639",
        "tertiary": "#fff7f6",
        "surface-container-highest": "#353534",
        "error": "#ffb4ab",
        "secondary-container": "#d05bff",
        "on-background": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "skate-jade": "#00ff41",
        "skate-obsidian": "#ff3333",
        "skate-obsidian-air": "#b026ff",
        "skate-obsidian-pro-air": "#ff6600",
        "skate-u9-air": "#ffaa00",
      },
      borderRadius: {
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1440px",
        "margin-mobile": "20px",
        "unit": "4px",
      },
      fontFamily: {
        "body-md": ["Geist", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "label-technical": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "label-technical": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
